name: Integration tests
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tagging
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: tagging

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install common dependencies
        run: pip install setuptools zc.buildout

      - name: Build library
        run: buildout

      # -----
      # MySQL
      # -----
      - name: Install OS dependencies for MySQL
        run: apt update && apt install -y gcc default-libmysqlclient-dev

      - name: Install Python dependencies for MySQL
        run: pip install mysqlclient

      - name: Run MySQL tests
        run: bin/test-and-cover
        env:
          DATABASE_ENGINE: mysql

      # -----
      # PostgreSQL
      # -----
      - name: Install Python dependencies for PostgreSQL
        run: pip install psycopg2-binary

      - name: Run Postgresql tests
        run: bin/test-and-cover
        env:
          DATABASE_ENGINE: postgres
